### ISSUE TITLE
Tracer-ui crashes when viewing an allocate-parties write transaction

### ISSUE THREAD

**Issue by scealiontach** [blockchaintp/daml-on-sawtooth#9] opened 2019-08-29 07:34 UTC
This may extend to more than allocating parties, but really it shouldn fail under any circumstance

Steps to reproduce
1. build the environment
1. `docker-compose -f docker/compose/daml-local.yaml up`
1. open a browser to `http://localhost:80` and select the write tab
1. `daml ledger allocate-parties --host localhost --port 9000 Alice`
1. browser view breaks as seen below
![Tracer-ui crash 2019-08-29 02-30-37](https://user-images.githubusercontent.com/20058097/63920017-849c6500-ca05-11e9-94a0-5a42ff6e2fba.png)

**Comment by paulwizviz** [comment] 2019-09-03 23:57
A fix has been made. It was caused by rpc producing badly formed JSON. Fix awaiting review by code owners.

**Comment by paulwizviz** [comment] 2019-09-05 17:03
Please checkout/pull the latest fix.

**Closed** 2019-09-05 17:03 UTC
Labels: bug
